declare const webpack: any;
declare const path: any;
declare const FriendlyErrorsWebpackPlugin: any;
declare const HtmlWebpackPlugin: any;
declare const AddAssetHtmlPlugin: any;
declare const ForkTsCheckerWebpackPlugin: any;
declare const ForkTsCheckerNotifierWebpackPlugin: any;
declare const NyanProgressPlugin: any;
declare const PATH: any;
